# Generated by Django 5.1 on 2024-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topsongs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.FileField(upload_to='images')),
                ('movie', models.CharField(max_length=1000)),
            ],
        ),
    ]
